using EssPortal.Web.Blazor.Enums.NavEnums;

namespace EssPortal.Web.Blazor.Models.Navision;

public class EmployeeCard
{
    public string? Key { get; set; }
    public string? No { get; set; }
    public string? FirstName { get; set; }
    public string? MiddleName { get; set; }
    public string? LastName { get; set; }
    public string? OtherName { get; set; }
    public string? JobTitle { get; set; }
    public string? Initials { get; set; }
    public string? SearchName { get; set; }
    public Gender Gender { get; set; }
    public bool GenderSpecified { get; set; }
    public string? PhoneNo2 { get; set; }
    public string? CompanyEmail { get; set; }
    public DateTime LastDateModified { get; set; }
    public bool LastDateModifiedSpecified { get; set; }
    public bool PrivacyBlocked { get; set; }
    public bool PrivacyBlockedSpecified { get; set; }
    public string? UserID { get; set; }
    public string? ManagerSupervisor { get; set; }
    public string? GlobalDimension1Code { get; set; }
    public string? GlobalDimension2Code { get; set; }
    public string? ResponsibilityCenter { get; set; }
    public string? Address { get; set; }
    public string? Address2 { get; set; }
    public string? City { get; set; }
    public string? County { get; set; }
    public string? PostCode { get; set; }
    public string? CountryRegionCode { get; set; }
    public string? ShowMap { get; set; }
    public string? MobilePhoneNo { get; set; }
    public string? Pager { get; set; }
    public string? Extension { get; set; }
    public string? Email { get; set; }
    public string? AltAddressCode { get; set; }
    public DateTime AltAddressStartDate { get; set; }
    public bool AltAddressStartDateSpecified { get; set; }
    public DateTime AltAddressEndDate { get; set; }
    public bool AltAddressEndDateSpecified { get; set; }
    public string? JobPosition { get; set; }
    public string? JobPositionTitle { get; set; }
    public string? SecondaryJobPosition { get; set; }
    public string? SecondaryJobPositionTitle { get; set; }
    public Employment_Type EmploymentType { get; set; }
    public bool EmploymentTypeSpecified { get; set; }
    public string? ContractType { get; set; }
    public string? ContractNumber { get; set; }
    public string? ContractLength { get; set; }
    public DateTime ContractStartDate { get; set; }
    public bool ContractStartDateSpecified { get; set; }
    public DateTime ContractEndDate { get; set; }
    public bool ContractEndDateSpecified { get; set; }
    public string? ActingNo { get; set; }
    public string? Control58 { get; set; }
    public string? ActingDescription { get; set; }
    public string? RelievedEmployee { get; set; }
    public string? RelievedName { get; set; }
    public DateTime StartDate { get; set; }
    public bool StartDateSpecified { get; set; }
    public DateTime EndDate { get; set; }
    public bool EndDateSpecified { get; set; }
    public string? ReasonForActing { get; set; }
    public DateTime EmploymentDate { get; set; }
    public bool EmploymentDateSpecified { get; set; }
    public EmployeeCardStatus Status { get; set; }
    public bool StatusSpecified { get; set; }
    public DateTime InactiveDate { get; set; }
    public bool InactiveDateSpecified { get; set; }
    public string? CauseOfInactivityCode { get; set; }
    public string? InactiveDescription { get; set; }
    public DateTime TerminationDate { get; set; }
    public bool TerminationDateSpecified { get; set; }
    public string? GroundsForTermCode { get; set; }
    public string? EmploymentContractCode { get; set; }
    public string? StatisticsGroupCode { get; set; }
    public string? ResourceNo { get; set; }
    public string? SalespersonPurchCode { get; set; }
    public DateTime BirthDate { get; set; }
    public bool BirthDateSpecified { get; set; }
    public string? SocialSecurityNo { get; set; }
    public string? UnionCode { get; set; }
    public string? UnionMembershipNo { get; set; }
    public Disabled Disabled { get; set; }
    public bool DisabledSpecified { get; set; }
    public string? Disability { get; set; }
    public string? DisabilityCertificate { get; set; }
    public string? DateOfBirthAge { get; set; }
    public string? IDNo { get; set; }
    public Marital_Status MaritalStatus { get; set; }
    public bool MaritalStatusSpecified { get; set; }
    public string? Religion { get; set; }
    public Ethnic_Origin EthnicOrigin { get; set; }
    public bool EthnicOriginSpecified { get; set; }
    public string? EthnicCommunity { get; set; }
    public string? EthnicName { get; set; }
    public string? HomeDistrict { get; set; }
    public string? FirstLanguage { get; set; }
    public string? SecondLanguage { get; set; }
    public string? OtherLanguage { get; set; }
    public string? EmployeePostingGroup { get; set; }
    public Application_Method ApplicationMethod { get; set; }
    public bool ApplicationMethodSpecified { get; set; }
    public string? BankBranchNo { get; set; }
    public string? BankAccountNo { get; set; }
    public string? IBAN { get; set; }
    public string? SWIFTCode { get; set; }
    public string? BOSAMemberNo { get; set; }
    public string? FOSAAccountNo { get; set; }
    public string? PINNumber { get; set; }
    public string? NHIFNo { get; set; }
    public string? PayMode { get; set; }
    public string? EmployeesBank { get; set; }
    public string? EmployeeBankName { get; set; }
    public string? BankBranch { get; set; }
    public string? EmployeeBranchName { get; set; }
    public string? EmployeeBankSortCode { get; set; }
    public string? BankAccountNumber { get; set; }
    public string? PostingGroup { get; set; }
    public string? GratuityVendorNo { get; set; }
    public string? DebtorCode { get; set; }
    public Employee_Type EmployeeType { get; set; }
    public bool EmployeeTypeSpecified { get; set; }
    public string? SalaryScale { get; set; }
    public string? Present { get; set; }
    public string? PreviousSalaryScale { get; set; }
    public string? Previous { get; set; }
    public string? Halt { get; set; }
    public bool PaysTax { get; set; }
    public bool PaysTaxSpecified { get; set; }
    public bool SecondaryEmployee { get; set; }
    public bool SecondaryEmployeeSpecified { get; set; }
    public bool InsuranceRelief { get; set; }
    public bool InsuranceReliefSpecified { get; set; }
    public bool ProRataCalculated { get; set; }
    public bool ProRataCalculatedSpecified { get; set; }
    public decimal CurrentBasicPay { get; set; }
    public bool CurrentBasicPaySpecified { get; set; }
    public decimal BasicPay { get; set; }
    public bool BasicPaySpecified { get; set; }
    public decimal HouseAllowance { get; set; }
    public bool HouseAllowanceSpecified { get; set; }
    public decimal InsurancePremium { get; set; }
    public bool InsurancePremiumSpecified { get; set; }
    public decimal TotalAllowances { get; set; }
    public bool TotalAllowancesSpecified { get; set; }
    public decimal TotalDeductions { get; set; }
    public bool TotalDeductionsSpecified { get; set; }
    public decimal TaxableAllowance { get; set; }
    public bool TaxableAllowanceSpecified { get; set; }
    public decimal CumulativePAYE { get; set; }
    public bool CumulativePAYESpecified { get; set; }
    public DateTime DateOfJoin { get; set; }
    public bool DateOfJoinSpecified { get; set; }
    public string? EmploymentDateAge { get; set; }
    public string? ProbationPeriod { get; set; }
    public DateTime EndOfProbationDate { get; set; }
    public bool EndOfProbationDateSpecified { get; set; }
    public DateTime PensionSchemeJoinDate { get; set; }
    public bool PensionSchemeJoinDateSpecified { get; set; }
    public DateTime MedicalSchemeJoinDate { get; set; }
    public bool MedicalSchemeJoinDateSpecified { get; set; }
    public DateTime RetirementDate { get; set; }
    public bool RetirementDateSpecified { get; set; }
    public string? NoticePeriod { get; set; }
    public string? SendAlertTo { get; set; }
    public bool ServedNoticePeriod { get; set; }
    public bool ServedNoticePeriodSpecified { get; set; }
    public DateTime DateOfLeaving { get; set; }
    public bool DateOfLeavingSpecified { get; set; }
    public Termination_Category TerminationCategory { get; set; }
    public bool TerminationCategorySpecified { get; set; }
    public DateTime ExitInterviewDate { get; set; }
    public bool ExitInterviewDateSpecified { get; set; }
    public string? ExitInterviewDoneBy { get; set; }
    public bool AllowReEmploymentInFuture { get; set; }
    public bool AllowReEmploymentInFutureSpecified { get; set; }
    public string? IncrementalMonth { get; set; }
    public DateTime LastIncrementDate { get; set; }
    public bool LastIncrementDateSpecified { get; set; }
    public DateTime NextIncrementDate { get; set; }
    public bool NextIncrementDateSpecified { get; set; }

}
