namespace ESSPortal.Domain.NavEntities;

public class EmployeeCard
{
    public string? No { get; set; }
    public string? First_Name { get; set; }
    public string? Middle_Name { get; set; }
    public string? Last_Name { get; set; }
    public string? Other_Name { get; set; }
    public string? Job_Title { get; set; }
    public string? Initials { get; set; }
    public string? Search_Name { get; set; }
    public string? Gender { get; set; }
    public string? Phone_No_2 { get; set; }
    public string? Company_E_Mail { get; set; }
    public DateTime? Last_Date_Modified { get; set; }
    public bool? Privacy_Blocked { get; set; }
    public string? User_ID { get; set; }
    public string? Manager_Supervisor { get; set; }
    public string? Global_Dimension_1_Code { get; set; }
    public string? Global_Dimension_2_Code { get; set; }
    public string? Responsibility_Center { get; set; }
    public string? Address { get; set; }
    public string? Address_2 { get; set; }
    public string? City { get; set; }
    public string? County { get; set; }
    public string? Post_Code { get; set; }
    public string? Country_Region_Code { get; set; }
    public string? ShowMap { get; set; }
    public string? Mobile_Phone_No { get; set; }
    public string? Pager { get; set; }
    public string? Extension { get; set; }
    public string? E_Mail { get; set; }
    public string? Alt_Address_Code { get; set; }
    public DateTime? Alt_Address_Start_Date { get; set; }
    public DateTime? Alt_Address_End_Date { get; set; }
    public string? Job_Position { get; set; }
    public string? Job_Position_Title { get; set; }
    public string? Secondary_Job_Position { get; set; }
    public string? Secondary_Job_Position_Title { get; set; }
    public string? Employment_Type { get; set; }
    public string? Contract_Type { get; set; }
    public string? Contract_Number { get; set; }
    public string? Contract_Length { get; set; }
    public DateTime? Contract_Start_Date { get; set; }
    public DateTime? Contract_End_Date { get; set; }
    public string? Acting_No { get; set; }
    public string? Control58 { get; set; }
    public string? Acting_Description { get; set; }
    public string? Relieved_Employee { get; set; }
    public string? Relieved_Name { get; set; }
    public DateTime? Start_Date { get; set; }
    public DateTime? End_Date { get; set; }
    public string? Reason_for_Acting { get; set; }
    public DateTime? Employment_Date { get; set; }
    public string? Status { get; set; }
    public DateTime? Inactive_Date { get; set; }
    public string? Cause_of_Inactivity_Code { get; set; }
    public string? InactiveDescription { get; set; }
    public DateTime? Termination_Date { get; set; }
    public string? Grounds_for_Term_Code { get; set; }
    public string? Emplymt_Contract_Code { get; set; }
    public string? Statistics_Group_Code { get; set; }
    public string? Resource_No { get; set; }
    public string? Salespers_Purch_Code { get; set; }
    public DateTime Birth_Date { get; set; }
    public string? Social_Security_No { get; set; }
    public string? Union_Code { get; set; }
    public string? Union_Membership_No { get; set; }
    public string? Disabled { get; set; }
    public string? Disability { get; set; }
    public string? Disability_Certificate { get; set; }
    public string? Date_of_Birth_Age { get; set; }
    public string? ID_No { get; set; }
    public string? Marital_Status { get; set; }
    public string? Religion { get; set; }
    public string? Ethnic_Origin { get; set; }
    public string? Ethnic_Community { get; set; }
    public string? Ethnic_Name { get; set; }
    public string? Home_District { get; set; }
    public string? First_Language { get; set; }
    public string? Second_Language { get; set; }
    public string? Other_Language { get; set; }
    public string? Employee_Posting_Group { get; set; }
    public string? Application_Method { get; set; }
    public string? Bank_Branch_No { get; set; }
    public string? Bank_Account_No { get; set; }
    public string? IBAN { get; set; }
    public string? SWIFT_Code { get; set; }
    public string? BOSA_Member_No { get; set; }
    public string? FOSA_Account_No { get; set; }
    public string? PIN_Number { get; set; }
    public string? NHIF_No { get; set; }
    public string? Pay_Mode { get; set; }
    public string? Employee_x0027_s_Bank { get; set; }
    public string? Employee_Bank_Name { get; set; }
    public string? Bank_Branch { get; set; }
    public string? Employee_Branch_Name { get; set; }
    public string? Employee_Bank_Sort_Code { get; set; }
    public string? Bank_Account_Number { get; set; }
    public string? Posting_Group { get; set; }
    public string? Gratuity_Vendor_No { get; set; }
    public string? Debtor_Code { get; set; }
    public string? Employee_Type { get; set; }
    public bool? Exempt_from_one_third_rule { get; set; }
    public string? Salary_Scale { get; set; }
    public string? Present { get; set; }
    public string? Previous_Salary_Scale { get; set; }
    public string? Previous { get; set; }
    public string? Halt { get; set; }
    public bool? Pays_tax_x003F_ { get; set; }
    public bool? Secondary_Employee { get; set; }
    public bool? Insurance_Relief { get; set; }
    public bool? Pro_Rata_Calculated { get; set; }
    public decimal? CurrBasicPay { get; set; }
    public decimal? Basic_Pay { get; set; }
    public decimal? House_Allowance { get; set; }
    public decimal? Insurance_Premium { get; set; }
    public decimal? Total_Allowances { get; set; }
    public decimal? Total_Deductions { get; set; }
    public decimal? Taxable_Allowance { get; set; }
    public decimal? Cumm_PAYE { get; set; }
    public DateTime Date_Of_Join { get; set; }
    public string? Employment_Date_Age { get; set; }
    public string? Probation_Period { get; set; }
    public DateTime? End_Of_Probation_Date { get; set; }
    public DateTime? Pension_Scheme_Join { get; set; }
    public DateTime? Medical_Scheme_Join { get; set; }
    public DateTime? Retirement_Date { get; set; }
    public string? Notice_Period { get; set; }
    public string? Send_Alert_to { get; set; }
    public bool? Served_Notice_Period { get; set; }
    public DateTime? Date_Of_Leaving { get; set; }
    public string? Termination_Category { get; set; }
    public DateTime? Exit_Interview_Date { get; set; }
    public string? Exit_Interview_Done_by { get; set; }
    public bool? Allow_Re_Employment_In_Future { get; set; }
    public string? Incremental_Month { get; set; }
    public DateTime? Last_Increment_Date { get; set; }
    public DateTime? Next_Increment_Date { get; set; }
    public DateTime? Last_Date_Increment { get; set; }
    public DateTime? Next_Date_Increment { get; set; }
    public string? Pay_Period_Filter { get; set; }
}
