namespace ESSPortal.Application.Dtos.Employee;
public record CreateEmployeeCardRequest(
    // Basic Information
    string? No,
    string? First_Name,
    string? Middle_Name,
    string? Last_Name,
    string? Other_Name,
    string? Job_Title,
    string? Initials,
    string? Search_Name,
    string? Gender,
    string? Phone_No_2,
    string? Company_E_Mail,
    DateTime? Last_Date_Modified,
    bool? Privacy_Blocked,
    string? User_ID,
    string? Manager_Supervisor,
    string? Global_Dimension_1_Code,
    string? Global_Dimension_2_Code,
    string? Responsibility_Center,

    // Address Information
    string? Address,
    string? Address_2,
    string? City,
    string? County,
    string? Post_Code,
    string? Country_Region_Code,
    string? ShowMap,

    // Contact Information
    string? Mobile_Phone_No,
    string? Pager,
    string? Extension,
    string? E_Mail,
    string? Alt_Address_Code,
    DateTime? Alt_Address_Start_Date,
    DateTime? Alt_Address_End_Date,

    // Job Information
    string? Job_Position,
    string? Job_Position_Title,
    string? Secondary_Job_Position,
    string? Secondary_Job_Position_Title,
    string? Employment_Type,
    string? Contract_Type,
    string? Contract_Number,
    string? Contract_Length,
    DateTime? Contract_Start_Date,
    DateTime? Contract_End_Date,

    // Acting Information
    string? Acting_No,
    string? Control58,
    string? Acting_Description,
    string? Relieved_Employee,
    string? Relieved_Name,
    DateTime? Start_Date,
    DateTime? End_Date,
    string? Reason_for_Acting,

    // Employment Status
    DateTime? Employment_Date,
    string? Status,
    DateTime? Inactive_Date,
    string? Cause_of_Inactivity_Code,
    string? InactiveDescription,
    DateTime? Termination_Date,
    string? Grounds_for_Term_Code,
    string? Emplymt_Contract_Code,
    string? Statistics_Group_Code,
    string? Resource_No,
    string? Salespers_Purch_Code,

    // Personal Information
    DateTime Birth_Date,
    string? Social_Security_No,
    string? Union_Code,
    string? Union_Membership_No,
    string? Disabled,
    string? Disability,
    string? Disability_Certificate,
    string? Date_of_Birth_Age,
    string? ID_No,
    string? Marital_Status,
    string? Religion,
    string? Ethnic_Origin,
    string? Ethnic_Community,
    string? Ethnic_Name,
    string? Home_District,
    string? First_Language,
    string? Second_Language,
    string? Other_Language,

    // Financial Information
    string? Employee_Posting_Group,
    string? Application_Method,
    string? Bank_Branch_No,
    string? Bank_Account_No,
    string? IBAN,
    string? SWIFT_Code,
    string? BOSA_Member_No,
    string? FOSA_Account_No,
    string? PIN_Number,
    string? NHIF_No,
    string? Pay_Mode,
    string? Employee_x0027_s_Bank,
    string? Employee_Bank_Name,
    string? Bank_Branch,
    string? Employee_Branch_Name,
    string? Employee_Bank_Sort_Code,
    string? Bank_Account_Number,
    string? Posting_Group,
    string? Gratuity_Vendor_No,
    string? Debtor_Code,
    string? Employee_Type,
    bool? Exempt_from_one_third_rule,

    // Salary Information
    string? Salary_Scale,
    string? Present,
    string? Previous_Salary_Scale,
    string? Previous,
    string? Halt,
    bool? Pays_tax_x003F_,
    bool? Secondary_Employee,
    bool? Insurance_Relief,
    bool? Pro_Rata_Calculated,
    decimal? CurrBasicPay,
    decimal? Basic_Pay,
    decimal? House_Allowance,
    decimal? Insurance_Premium,
    decimal? Total_Allowances,
    decimal? Total_Deductions,
    decimal? Taxable_Allowance,
    decimal? Cumm_PAYE,

    // Employment Dates and Periods
    DateTime Date_Of_Join,
    string? Employment_Date_Age,
    string? Probation_Period,
    DateTime? End_Of_Probation_Date,
    DateTime? Pension_Scheme_Join,
    DateTime? Medical_Scheme_Join,
    DateTime? Retirement_Date,
    string? Notice_Period,
    string? Send_Alert_to,
    bool? Served_Notice_Period,
    DateTime? Date_Of_Leaving,
    string? Termination_Category,
    DateTime? Exit_Interview_Date,
    string? Exit_Interview_Done_by,
    bool? Allow_Re_Employment_In_Future,

    // Increment Information
    string? Incremental_Month,
    DateTime? Last_Increment_Date,
    DateTime? Next_Increment_Date,
    DateTime? Last_Date_Increment,
    DateTime? Next_Date_Increment,
    string? Pay_Period_Filter

    );
