using EssPortal.Domain.Enums.NavEnums;
using ESSPortal.Application.Dtos.ModelFilters;

namespace EssPortal.Application.Dtos.ModelFilters;

public record EmployeeCardFilter : BaseFilter
{
    public string? No { get; init; }
    public string? FirstName { get; init; }
    public string? MiddleName { get; init; }
    public string? LastName { get; init; }
    public string? OtherName { get; init; }
    public string? JobTitle { get; init; }
    public string? Initials { get; init; }
    public string? SearchName { get; init; }
    public string? PhoneNo2 { get; init; }
    public string? CompanyEMail { get; init; }
    public string? LastDateModified { get; init; }
    public string? PrivacyBlocked { get; init; }
    public string? UserId { get; init; }
    public string? ManagerSupervisor { get; init; }
    public string? GlobalDimension1Code { get; init; }
    public string? GlobalDimension2Code { get; init; }
    public string? Responsibility_Center { get; init; }
    public string? Address { get; init; }
    public string? Address2 { get; init; }
    public string? City { get; init; }
    public string? County { get; init; }
    public string? PostCode { get; init; }
    public string? CountryRegionCode { get; init; }
    public string? ShowMap { get; init; }
    public string? MobilePhoneNo { get; init; }
    public string? Pager { get; init; }
    public string? Extension { get; init; }
    public string? EMail { get; init; }
    public string? AltAddressCode { get; init; }
    public string? AltAddressStartDate { get; init; }
    public string? AltAddressEndDate { get; init; }
    public string? JobPosition { get; init; }
    public string? JobPositionTitle { get; init; }
    public string? SecondaryJobPosition { get; init; }
    public string? SecondaryJobPositionTitle { get; init; }
    public string? ContractType { get; init; }
    public string? ContractNumber { get; init; }
    public string? ContractLength { get; init; }
    public string? ContractStartDate { get; init; }
    public string? ContractEndDate { get; init; }
    public string? ActingNo { get; init; }
    public string? Control58 { get; init; }
    public string? ActingDescription { get; init; }
    public string? RelievedEmployee { get; init; }
    public string? RelievedName { get; init; }
    public string? StartDate { get; init; }
    public string? EndDate { get; init; }
    public string? ReasonForActing { get; init; }
    public string? EmploymentDate { get; init; }
    public string? InactiveDate { get; init; }
    public string? CauseOfInactivityCode { get; init; }
    public string? InactiveDescription { get; init; }
    public string? TerminationDate { get; init; }
    public string? GroundsForTermCode { get; init; }
    public string? EmplymtContractCode { get; init; }
    public string? StatisticsGroupCode { get; init; }
    public string? ResourceNo { get; init; }
    public string? SalespersPurchCode { get; init; }
    public string? BirthDate { get; init; }
    public string? SocialSecurityNo { get; init; }
    public string? UnionCode { get; init; }
    public string? UnionMembershipNo { get; init; }
    public string? Disability { get; init; }
    public string? DisabilityCertificate { get; init; }
    public string? DateOfBirthAge { get; init; }
    public string? IdNo { get; init; }
    public string? Religion { get; init; }
    public string? EthnicCommunity { get; init; }
    public string? EthnicName { get; init; }
    public string? HomeDistrict { get; init; }
    public string? FirstLanguage { get; init; }
    public string? SecondLanguage { get; init; }
    public string? OtherLanguage { get; init; }
    public string? EmployeePostingGroup { get; init; }
    public string? BankBranchNo { get; init; }
    public string? BankAccountNo { get; init; }
    public string? Iban { get; init; }
    public string? SwiftCode { get; init; }
    public string? BosaMemberNo { get; init; }
    public string? FosaAccountNo { get; init; }
    public string? PinNumber { get; init; }
    public string? NhifNo { get; init; }
    public string? PayMode { get; init; }
    public string? EmployeesBank { get; init; }
    public string? EmployeeBankName { get; init; }
    public string? BankBranch { get; init; }
    public string? EmployeeBranchName { get; init; }
    public string? EmployeeBankSortCode { get; init; }
    public string? BankAccountNumber { get; init; }
    public string? PostingGroup { get; init; }
    public string? GratuityVendorNo { get; init; }
    public string? DebtorCode { get; init; }
    public string? SalaryScale { get; init; }
    public string? Present { get; init; }
    public string? PreviousSalaryScale { get; init; }
    public string? Previous { get; init; }
    public string? Halt { get; init; }
    public string? PaysTax { get; init; }
    public string? SecondaryEmployee { get; init; }
    public string? InsuranceRelief { get; init; }
    public string? ProRataCalculated { get; init; }
    public string? CurrBasicPay { get; init; }
    public string? BasicPay { get; init; }
    public string? HouseAllowance { get; init; }
    public string? InsurancePremium { get; init; }
    public string? TotalAllowances { get; init; }
    public string? TotalDeductions { get; init; }
    public string? TaxableAllowance { get; init; }
    public string? CummPaye { get; init; }
    public string? DateOfJoin { get; init; }
    public string? EmploymentDateAge { get; init; }
    public string? ProbationPeriod { get; init; }
    public string? EndOfProbationDate { get; init; }
    public string? PensionSchemeJoin { get; init; }
    public string? MedicalSchemeJoin { get; init; }
    public string? RetirementDate { get; init; }
    public string? NoticePeriod { get; init; }
    public string? SendAlertTo { get; init; }
    public string? ServedNoticePeriod { get; init; }
    public string? DateOfLeaving { get; init; }
    public string? ExitInterviewDate { get; init; }
    public string? ExitInterviewDoneBy { get; init; }
    public string? AllowReEmploymentInFuture { get; init; }
    public string? IncrementalMonth { get; init; }
    public string? LastIncrementDate { get; init; }
    public string? NextIncrementDate { get; init; }
    public Gender? Gender { get; init; }
    public Employee_Type? EmploymentType { get; init; }
    public EmployeesStatus? Status { get; init; }
    public EmployeeCardStatus? Disabled { get; init; }
    public Marital_Status? MaritalStatus { get; init; }
    public Ethnic_Origin? EthnicOrigin { get; init; }
    public Application_Method? ApplicationMethod { get; init; }
    public Employee_Type? EmployeeType { get; init; }
    public Termination_Category? TerminationCategory { get; init; }
}
